/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package eu.spaziodati.poldini.avro;  
@SuppressWarnings("all")
/** doc */
@org.apache.avro.specific.AvroGenerated
public class Page extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Page\",\"namespace\":\"eu.spaziodati.poldini.avro\",\"doc\":\"doc\",\"fields\":[{\"name\":\"url\",\"type\":\"string\"},{\"name\":\"content\",\"type\":\"string\"},{\"name\":\"debug\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence url;
  @Deprecated public java.lang.CharSequence content;
  @Deprecated public java.lang.CharSequence debug;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Page() {}

  /**
   * All-args constructor.
   */
  public Page(java.lang.CharSequence url, java.lang.CharSequence content, java.lang.CharSequence debug) {
    this.url = url;
    this.content = content;
    this.debug = debug;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return url;
    case 1: return content;
    case 2: return debug;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: url = (java.lang.CharSequence)value$; break;
    case 1: content = (java.lang.CharSequence)value$; break;
    case 2: debug = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'url' field.
   */
  public java.lang.CharSequence getUrl() {
    return url;
  }

  /**
   * Sets the value of the 'url' field.
   * @param value the value to set.
   */
  public void setUrl(java.lang.CharSequence value) {
    this.url = value;
  }

  /**
   * Gets the value of the 'content' field.
   */
  public java.lang.CharSequence getContent() {
    return content;
  }

  /**
   * Sets the value of the 'content' field.
   * @param value the value to set.
   */
  public void setContent(java.lang.CharSequence value) {
    this.content = value;
  }

  /**
   * Gets the value of the 'debug' field.
   */
  public java.lang.CharSequence getDebug() {
    return debug;
  }

  /**
   * Sets the value of the 'debug' field.
   * @param value the value to set.
   */
  public void setDebug(java.lang.CharSequence value) {
    this.debug = value;
  }

  /** Creates a new Page RecordBuilder */
  public static eu.spaziodati.poldini.avro.Page.Builder newBuilder() {
    return new eu.spaziodati.poldini.avro.Page.Builder();
  }
  
  /** Creates a new Page RecordBuilder by copying an existing Builder */
  public static eu.spaziodati.poldini.avro.Page.Builder newBuilder(eu.spaziodati.poldini.avro.Page.Builder other) {
    return new eu.spaziodati.poldini.avro.Page.Builder(other);
  }
  
  /** Creates a new Page RecordBuilder by copying an existing Page instance */
  public static eu.spaziodati.poldini.avro.Page.Builder newBuilder(eu.spaziodati.poldini.avro.Page other) {
    return new eu.spaziodati.poldini.avro.Page.Builder(other);
  }
  
  /**
   * RecordBuilder for Page instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Page>
    implements org.apache.avro.data.RecordBuilder<Page> {

    private java.lang.CharSequence url;
    private java.lang.CharSequence content;
    private java.lang.CharSequence debug;

    /** Creates a new Builder */
    private Builder() {
      super(eu.spaziodati.poldini.avro.Page.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(eu.spaziodati.poldini.avro.Page.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.url)) {
        this.url = data().deepCopy(fields()[0].schema(), other.url);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.content)) {
        this.content = data().deepCopy(fields()[1].schema(), other.content);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.debug)) {
        this.debug = data().deepCopy(fields()[2].schema(), other.debug);
        fieldSetFlags()[2] = true;
      }
    }
    
    /** Creates a Builder by copying an existing Page instance */
    private Builder(eu.spaziodati.poldini.avro.Page other) {
            super(eu.spaziodati.poldini.avro.Page.SCHEMA$);
      if (isValidValue(fields()[0], other.url)) {
        this.url = data().deepCopy(fields()[0].schema(), other.url);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.content)) {
        this.content = data().deepCopy(fields()[1].schema(), other.content);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.debug)) {
        this.debug = data().deepCopy(fields()[2].schema(), other.debug);
        fieldSetFlags()[2] = true;
      }
    }

    /** Gets the value of the 'url' field */
    public java.lang.CharSequence getUrl() {
      return url;
    }
    
    /** Sets the value of the 'url' field */
    public eu.spaziodati.poldini.avro.Page.Builder setUrl(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.url = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'url' field has been set */
    public boolean hasUrl() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'url' field */
    public eu.spaziodati.poldini.avro.Page.Builder clearUrl() {
      url = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'content' field */
    public java.lang.CharSequence getContent() {
      return content;
    }
    
    /** Sets the value of the 'content' field */
    public eu.spaziodati.poldini.avro.Page.Builder setContent(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.content = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'content' field has been set */
    public boolean hasContent() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'content' field */
    public eu.spaziodati.poldini.avro.Page.Builder clearContent() {
      content = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'debug' field */
    public java.lang.CharSequence getDebug() {
      return debug;
    }
    
    /** Sets the value of the 'debug' field */
    public eu.spaziodati.poldini.avro.Page.Builder setDebug(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.debug = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'debug' field has been set */
    public boolean hasDebug() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'debug' field */
    public eu.spaziodati.poldini.avro.Page.Builder clearDebug() {
      debug = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    public Page build() {
      try {
        Page record = new Page();
        record.url = fieldSetFlags()[0] ? this.url : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.content = fieldSetFlags()[1] ? this.content : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.debug = fieldSetFlags()[2] ? this.debug : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
